### ISSUE TITLE
Add a button in the About Us page to navigate back to the Home page

### ISSUE THREAD

**Issue by TBorundia** [GameSphere-MultiPlayer/Physi-c-Tech#109]
As part of the website improvements under GSSoC'24, I propose adding a button on the "About Us" page that allows users to navigate back to the Home page easily.

- Add a button styled consistently with the website's design.
- Ensure the button is responsive and works well on both desktop and mobile devices.
- Link the button to the Home page.

I would like to work on this issue. Could you please assign it to me?

**Comment by arunimasharma33** [comment]
Please assign this issue to me. I would like to fix it.

**Comment by soniya-malviy** [comment]
i would like to solve this issue please assign me this issue
