### ISSUE TITLE
[New Feature]: Missing Feedback Form on Game

### ISSUE THREAD

**Issue by AkshitGarg24** [GameSphere-MultiPlayer/Physi-c-Tech#110]
### 🎮 feature Request

The game lacks a feedback form, which limits user interaction and prevents the collection of valuable user insights and suggestions.

### Point down the features

To address this issue, I will integrate a user-friendly feedback form. The form should include fields for:

- Name
- Email
- Rating (eg 1-5 stars)
- Comments/Suggestions

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
When will the user be asked to fill out the feedback form? If you just create an another button for feedback, no one will put an extra effort for just filling out a form. Eighter you will have to prompt the player between the game to fill the feedback form, but it will degrade the gaming experience. And how will you store the feedback data for the admin to see? Answer these questions after which I will assign you the issue.

**Comment by AkshitGarg24** [comment]
Instead of integrating a feedback form directly into the game flow, we can add a button on the main page labeled "Facing an Issue? Help Us Improve!" This way, players can click the button whenever they encounter technical glitches or have suggestions for improvements and new features.

Regarding the data storage aspect, I can handle the front-end implementation of this feature. For storing and managing the feedback data, this part could be assigned to someone else who is experienced with backend development.

**Comment by thevirengarg** [comment]
> Instead of integrating a feedback form directly into the game flow, we can add a button on the main page labeled "Facing an Issue? Help Us Improve!" This way, players can click the button whenever they encounter technical glitches or have suggestions for improvements and new features.
> 
> Regarding the data storage aspect, I can handle the front-end implementation of this feature. For storing and managing the feedback data, this part could be assigned to someone else who is experienced with backend development.

Make sure the button should look minimal and blend with the theme.

**Comment by AkshitGarg24** [comment]
> > Instead of integrating a feedback form directly into the game flow, we can add a button on the main page labeled "Facing an Issue? Help Us Improve!" This way, players can click the button whenever they encounter technical glitches or have suggestions for improvements and new features.
> > Regarding the data storage aspect, I can handle the front-end implementation of this feature. For storing and managing the feedback data, this part could be assigned to someone else who is experienced with backend development.
> 
> Make sure the button should look minimal and blend with the theme.

Sure

**Comment by AkshitGarg24** [comment]
Could you please add the level to this issue?

**Comment by thevirengarg** [comment]
I will add the level tag to the PR, as the points for the contribution will also matter in the design. There is no need for the issue to have a level tag; only the PR's label will count.
