### ISSUE TITLE
Implement scroll-to-top button in About page

### ISSUE THREAD

**Issue by TBorundia** [GameSphere-MultiPlayer/Physi-c-Tech#112]
Creating scroll-to-top button for improved user experience

- Implement a scroll-to-top button to enhance navigation.
- Provide users with an easy way to return to the top of the page.

Please assign this issue to me under GSSoC'24.

**Comment by thevirengarg** [comment]
> Creating scroll-to-top button for improved user experience
> 
> - Implement a scroll-to-top button to enhance navigation.
> - Provide users with an easy way to return to the top of the page.
> 
> Please assign this issue to me under GSSoC'24.

The website doesn't require scroll-to-top button
