### ISSUE TITLE
[New Feature]: Add new features 

### ISSUE THREAD

**Issue by GitNinja-bcd** [GameSphere-MultiPlayer/Physi-c-Tech#137]
### 🎮 feature Request

When we're scrolling down the page, it's not moving to the next page.
 We can add game-related information to the page so that when a user scrolls, the page moves and they see game-related information and we create some animation to look more attractive.
We can implement a scrolling feature on your webpage, where new content related to games is loaded as the user scrolls down. This can enhance user engagement and provide a seamless browsing experience.

![Screenshot (9)](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/158538244/44c8f669-6fd4-4588-a93c-c15645f58c83)

### Point down the features

This feature enhances user experience by implementing infinite scrolling on the webpage. As users scroll down, new game-related information dynamically loads, providing continuous engagement. 

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@GitNinja-bcd Game related content is already added in about page, don't need to write it twice.
