### ISSUE TITLE
Shifting the css files to a new style.css file

### ISSUE THREAD

**Issue by Sambit-Mondal** [GameSphere-MultiPlayer/Physi-c-Tech#16]
Shifting the CSS files to a new "style.css" file would make the code look clean and understandable by the users.

Please assign this issue to me under GSSoC '24.

Thank you!

**Comment by Durgesh4993** [comment]
@Sambit-Mondal Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Sambit-Mondal** [comment]
Sir, I've already linked a PR to this.

So, basically I want to shift the style (CSS) elements, present in the "index.html" file, under the tags <style>...</style>

![Screenshot 2024-05-12 120920](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138088550/f8084788-3020-4e09-ae3b-636e3169a023)

to a new file "style.css"

![Screenshot 2024-05-12 120958](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138088550/09b1be99-fe5b-48e3-96f7-5e9a16ac2967)



This would make the code look clean and more understandable to the users, if elements are stored in separate files.

Thank you!
