### ISSUE TITLE
[New Feature]: Enhancement style of the homepage.

### ISSUE THREAD

**Issue by AnirbanGhosh2** [GameSphere-MultiPlayer/Physi-c-Tech#17]
### 🎮 feature Request

- The landing page looks quite static.
- I can improve the UI of the homepage and make a better landing page with greater responsiveness.
- I will also change the fonts of the words and will a create a more attractive webpage.

Please assign me this under GSSOC'24 I will update and make proper responsive the home site.

### Point down the features

feature points-

1. Font style change
2. Will involve some animation that will show the page more attractive
3. Navbar with proper responsiveness
4. More attractive icons in the homepage

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@AnirbanGhosh2 Please raise any other issue, because this issue is already created

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
