### ISSUE TITLE
[Documentation]: Information about the game needed 

### ISSUE THREAD

**Issue by Ajita369** [GameSphere-MultiPlayer/Physi-c-Tech#24]
### Describe the bug ✍️

Can you please provide the details about how the game works . I can add those details in the readme.md file which will make the documentation of the project complete and it will also help beginners like me to understand the project in a better way.
also it is coming like this : 
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/162597493/e268967d-986c-42ef-9978-c77336667414)

### Provide step by step information reproduce the bug 📄

for people to understand the project in a better way documentaion is required. If you can give me details about the project I can add them in the readme file under GSSOC'24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by BagchiShreya** [comment]
Hello @Durgesh4993 I would like to work on this issue. It would be great if you assign this issue to me as I already have worked on similar issues and I think I would be able to resolve this issue.

**Comment by Durgesh4993** [comment]
@Ajita369 when we merge to different element they form a new elements, and using those element we form multiple elements

**Comment by Durgesh4993** [comment]
@BagchiShreya Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by NeerajaGurram** [comment]
I would like to make the documentation page(to be precise it more likely to be a web page) for how to play the game..and a logo that helps you in directing to the help page

I'm contributing to GSSoC'24 so please assign me this
