### ISSUE TITLE
[Enhancement]: Add a how to play or about game section

### ISSUE THREAD

**Issue by BagchiShreya** [GameSphere-MultiPlayer/Physi-c-Tech#26]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
When I, as a new user of the game, opened the game, I was a bit confused about what the game is about and what should a player do. After clicking the buttons and hints for several times I understood what the game does.

### Describe the solution you'd like

Solution steps
As a solution to this problem, I would like to include a 'how to play' or 'about game' section which explains the steps of the game to new users.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by BagchiShreya** [comment]
I as a GSSoC'24 contributor would like to work on this issue. As I have worked on similar issues for other projects and also have raised a number of PRs, I think I am capable to solve this issue. It would be great if @Durgesh4993 sir if you assign this issue to me.

This would be a GSSoC'24 contribution

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Ketanop321** [comment]
I would like to contribute in this issue as GSSoC'24 contributor. I hope you will assign me this issue @Durgesh4993 .
