### ISSUE TITLE
Game logo adding on the Website header[New Feature]

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [GameSphere-MultiPlayer/Physi-c-Tech#27]
### 🎮 feature Request

Game logo adding on the Website header

### Point down the features

![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/125277258/f4de0991-ac2b-4eb5-aea2-f2fbd17eae37)

i add the logo here 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shristipandey128** [comment]
@Durgesh4993 Please this issue

**Comment by Durgesh4993** [comment]
@shristipandey128 @RamakrushnaBiswal Please raise any other issue..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
