### ISSUE TITLE
[New Feature]: Adding a favicon Icon

### ISSUE THREAD

**Issue by devlohani99** [GameSphere-MultiPlayer/Physi-c-Tech#28]
### 🎮 feature Request

![Screenshot 2024-05-12 152912](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/142163543/17f5fa18-e0b2-4e88-bca8-67fc680dfcb6)

By adding a Favicon icon  enchances its overall apperrance

### Point down the features

-It will give website its logo and acts as hallmark for the users

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by devlohani99** [comment]
@Durgesh4993 Sir, Its my pleasure to work on it 
kindly assign the work

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by AshishKumarSamantaray** [comment]
Assign me for the same

**Comment by vardhini3103** [comment]
@Durgesh4993 Sir, I would like to work on this issue. Please assign it to me.

**Comment by uraj1** [comment]
@Durgesh4993 being an designer too, I can make a good favicon for the website , so I request you to kindly assign this to me
