### ISSUE TITLE
[Enhancement]: The whole Structure and Style of the website

### ISSUE THREAD

**Issue by PrathamAsrani** [GameSphere-MultiPlayer/Physi-c-Tech#29]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: 
1. The fonts are not comforting eyes.
2. Icons are not that good for the elements
3. Code is not modular and maintainable
4. Two scroll bars of (one of whole game and second of discovered section)
![Screenshot 2024-05-12 153722](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/114286503/57f60c3b-a130-4fbf-a059-e0d445bb307e)
6. The discovered section height is fixed looking unprofessional
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/114286503/a2ef35d8-e098-448b-a87a-4e7a2b59f8e1)

### Describe the solution you'd like

Solution steps
I want to style and restructure the whole game by adding:
1. The Industry standard Fonts for Headings and Text
2. Improve the Icons
3. Adding modularity to the codes and css files so that the code maintenance will be improved 
4. Removing one scroll bar, because there are two (looking not good) .
5. add the down section of discovered elements have so much space make it responsive in terms of automatically width increment when elements are found

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shristipandey128** [comment]
Please assign  me this issue @PrathamAsrani

**Comment by Durgesh4993** [comment]
@PrathamAsrani Could you please explain more what you want to do, if possible you can also add screenshot.
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Durgesh4993** [comment]
@shristipandey128 Please raise any other issue, i'll assign you

**Comment by PrathamAsrani** [comment]
Basically, the website needs improvement in terms of design like two scroll bars is not looking good & code structure files need to be separate and Linked, I want to provide that.
