### ISSUE TITLE
[Enhancement]: Adding more features and a good and dynamic oepning page

### ISSUE THREAD

**Issue by AshishKumarSamantaray** [GameSphere-MultiPlayer/Physi-c-Tech#32]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement
We can work on the opening page ui ux and then we can make the features visible while the user scroll down.

Kindly assign the issue to me.

### Describe the solution you'd like

Solution steps
I will create a figma ui ux then implement on code using gsap animation and bootstrap and then we will add some more features to this project and work on it even more.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shristipandey128** [comment]
Please assign me this issue @AshishKumarSamantaray

**Comment by Durgesh4993** [comment]
@shristipandey128 Please raise any other issue, i'll assign you..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Durgesh4993** [comment]
@AshishKumarSamantaray Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by AshishKumarSamantaray** [comment]
Would be making a some Figma designs today and will be sharing those with
you

**Comment by Durgesh4993** [comment]
Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
