### ISSUE TITLE
[Bug]: Spelling Error

### ISSUE THREAD

**Issue by SalehaTabassum** [GameSphere-MultiPlayer/Physi-c-Tech#34]
### Give a brief about the bug ✍️

I have found that when  we click the bulb for want more hints ...You can see that there is a spelling error "Foll" instead of "follow"

### What is the expected behavior? 🤔

Description
![Screenshot 2024-05-12 165423](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/169278740/ec6bf1d6-8ba4-4d48-a24a-729a11857d10)
 

### Provide step by step information reproduce the bug 📄

i would like to correct this spelling error.

@Durgesh4993 please assign me this issue under GSSOC 2024 and add necessary labels

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by shristipandey128** [comment]
Please assign me this issue, @SalehaTabassum

**Comment by Durgesh4993** [comment]
@shristipandey128 Please raise any other issue, i'll assign you...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by traptijindal** [comment]
please assign me this issue ..I will fix this issue for you..
