### ISSUE TITLE
[Bug]: Creating new file for style.css

### ISSUE THREAD

**Issue by SalehaTabassum** [GameSphere-MultiPlayer/Physi-c-Tech#36]
### Give a brief about the bug ✍️

As we can see that index.html contains the css code..It makes html and css code mix.I want to create a separate style.css

### What is the expected behavior? 🤔

Separate style.css

### Provide step by step information reproduce the bug 📄

 I will create a style.css file 
Please assign this issue to me @Durgesh4993 
Under GSSOC 2024 and add necessary labels 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by drashtigit** [comment]
Please assign this issue to me. would be happy to work on it.

**Comment by shristipandey128** [comment]
please assign me this, @SalehaTabassum

**Comment by Durgesh4993** [comment]
@shristipandey128 @drashtigit @SalehaTabassum Please raise any other issue, because someone is already working on it
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
