### ISSUE TITLE
[Enhancement]: The home page icon is difficult to identify until discovered . Create a hover effect to make it more understandable.

### ISSUE THREAD

**Issue by SIM-RAITANI** [GameSphere-MultiPlayer/Physi-c-Tech#39]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement: The small hut at the top left corner become very difficult to identify. The user will get confuse about its functionality. The home icon should be more understandable.

### Describe the solution you'd like

Either i can change the home icon or add a hover effect on it. As soon as user hover on it it will display home which will make the user understand that it is the home page icon.

### Select program in which you are contributing

GSSoC23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@SIM-RAITANI Could you please explain more what you want to do, if possible you can also add screenshot...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by vardhini3103** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by SIM-RAITANI** [comment]
> @SIM-RAITANI Could you please explain more what you want to do, if possible you can also add screenshot... If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...
> 
> Thank you :)

Sir i would add hover effect that will tell us that it is an home icon and it will take us to a new page. Such that when someone hover on it , on the bottom home should be written with it.
Like in the above image,the description comes upon hover.

![Screenshot 2024-05-13 180642](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/162676120/8bc5551b-40fd-48ae-be63-ce45d41aff99)

**Comment by KomalSrivastava** [comment]
@thevirengarg I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible About page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience.i can add hover effect in it.

**Comment by KomalSrivastava** [comment]
@thevirengarg I can improve https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/issues/39 and https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/issues/42 which is about home page button and icon assign me this task. I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible Home page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience. i will add hover effect in it.

**Comment by KomalSrivastava** [comment]
@thevirengarg I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible Home page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience. i will add hover effect in icon.

**Comment by thevirengarg** [comment]
@KomalSrivastava Create a new issue
