### ISSUE TITLE
[New Feature]:ADD a sound effect in the background. 

### ISSUE THREAD

**Issue by SIM-RAITANI** [GameSphere-MultiPlayer/Physi-c-Tech#40]
### 🎮 feature Request

Any game is incomplete without its music. I would add a sound effect in the background.

### Point down the features

I will search for a sound effect that matches with the game.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@SIM-RAITANI Please raise any other issue, because someone is already working on it...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
