### ISSUE TITLE
Missing CONTRIBUTING.md file and LEARN.md file in repository 

### ISSUE THREAD

**Issue by Braj-01** [GameSphere-MultiPlayer/Physi-c-Tech#45]
### Describe your question or ask for support.❓

The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Braj-01** [comment]
Please assign this task so that I can add these file for better user experience.

**Comment by alishasingh06** [comment]
please assign this task to me

**Comment by Suruchibharti** [comment]
hii ,
I'm GSSoC'24 contributor ,I want to work on this issue,
so, kindly requested to you to assign me the issue.

**Comment by Durgesh4993** [comment]
@Braj-01 please check.github folder, we already have code of conduct file
