### ISSUE TITLE
adding a background picture that suits the website game theme

### ISSUE THREAD

**Issue by sahithinandikula** [GameSphere-MultiPlayer/Physi-c-Tech#54]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

1)adding a background image 
2)  adding hover effects to the buttons 
This makes the page more interactive and attractive 
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/138794574/315cf998-c58e-461d-870d-6de1c8e93cc9)

### Describe the solution you'd like

solution steps
1) adding a background image 
2) applying hover effects on the buttons

### Select program in which you are contributing

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by sahithinandikula** [comment]
@Durgesh4993 I would like to work on this . hope will be assigned to me

**Comment by Bonnyyyy** [comment]
@Durgesh4993 I saw this issue on the website page, and want to fix it and give your project a good user experience. Please assign me to deliver it at earliest.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
