### ISSUE TITLE
[New Feature]: Proper Instructions Guide on how to play the game

### ISSUE THREAD

**Issue by r7projects-shayan** [GameSphere-MultiPlayer/Physi-c-Tech#55]
### 🎮 feature Request

The game can be very confusing for someone who is playing it for the first time. There is currently no instructions or help guides on how to play the game. 

### Point down the features

Properly structured guide on how to play the game

Video walkthroughs demonstrating the Guide

Separate interactive page for the instructions

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by r7projects-shayan** [comment]
Hey @Durgesh4993 kindly assign this issue to me. It's a major issue and needs to be solved soon. I will start working on it right after getting assigned

**Comment by Vaishnavigupta1312** [comment]
Would like to do resolve this issue in collaboration with you. @r7projects-shayan 
@Durgesh4993 Please assign it to us, also give the description of what the game intends to do.

**Comment by r7projects-shayan** [comment]
@Vaishnavigupta1312 I don't think more than once person can be assigned a task. If we get assigned together, message me at discord @starcoders

**Comment by Durgesh4993** [comment]
@r7projects-shayan Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
