### ISSUE TITLE
The Back button

### ISSUE THREAD

**Issue by Ajita369** [GameSphere-MultiPlayer/Physi-c-Tech#58]
### 🎮 feature Request

The back button at the top left corner don't show that it is back button . It is not convenient  for the user of the game.
Here is the screenshot :  
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/162597493/59dfa282-883a-4558-bca2-3aa755fcebb4)
I can make the needful changes so please assign this issue to me under GSSOC'24.

### Point down the features

I can make the needful changes so please assign this issue to me under GSSOC'24.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by diyaaa19** [comment]
i would like to work on this project. please assign me this issue.
thanks and regards

**Comment by Anjankumarkamalapur** [comment]
I want to work on this particular project can you please assign this to me.

**Comment by Durgesh4993** [comment]
@Anjankumarkamalapur @diyaaa19 @Ajita369 Please raise any other issue...
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
