### ISSUE TITLE
[Documentation Bug]:  Buttons Separation!

### ISSUE THREAD

**Issue by Anjaliavv51** [GameSphere-MultiPlayer/Physi-c-Tech#68]
### Describe the bug ✍️

Describe your bug here
Buttons in main/index.html are not separated!
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/f84cb62a-1909-45a0-adec-a539c6e9987d)
 

### Provide step by step information reproduce the bug 📄

Description

Separation of these buttons , gives clarity to the user.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anjaliavv51** [comment]
Please add GSSOC LABEL

**Comment by Durgesh4993** [comment]
@Anjaliavv51 Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Anjaliavv51** [comment]
Okay

**Comment by Anjaliavv51** [comment]
@Durgesh4993 PLAY NEWGAME SOUNDON these r very close to each other , so i would like to make them to button , to make clear view of them.

**Comment by thevirengarg** [comment]
@Anjaliavv51 Similar issue has already been assigned to someone else.
