### ISSUE TITLE
[New Feature]: Would like to add preloader?

### ISSUE THREAD

**Issue by Anjaliavv51** [GameSphere-MultiPlayer/Physi-c-Tech#71]
### 🎮 feature Request

feature logic and basic description
A preloader is an essential interface element that appears on a web page while its content is being loaded. It serves as a visual cue to users, letting them know that the website is actively processing data and hasn’t crashed.

### Point down the features

feature points
1.User Experience Enhancement
2.Visual Feedback
3.Customization
4.Responsive Interaction

Feature:

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/7ef2cd29-dc32-44db-9225-81f4d28bdc45

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Anjaliavv51** [comment]
Please add GSSOC label.

**Comment by Anjaliavv51** [comment]
Please add GSSOC label.

**Comment by Anjaliavv51** [comment]
@ayoush Kumar ,please check it think u commited ur files by mistakly to my issue

**Comment by Anjaliavv51** [comment]
https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/154777864/e1a402ef-5438-4d50-8a2b-73a388891abe

**Comment by Anjaliavv51** [comment]
@thevirengarg  please preview the changes and merge it!

**Comment by thevirengarg** [comment]
@Anjaliavv51 You are the contributor, you need to pitch a design for the preloader. I have already told you what I felt was not good about the previous one.

**Comment by Anjaliavv51** [comment]
Okay @thevirengarg

**Comment by Anjaliavv51** [comment]
@thevirengarg please review the changes and merge it!
