### ISSUE TITLE
[New Feature]: Add title to the navbar beside the home 

### ISSUE THREAD

**Issue by jayanththalla** [GameSphere-MultiPlayer/Physi-c-Tech#75]
### 🎮 feature Request

feature logic and basic description
Add Physi-c-Tech title to the home 
below bulb symbol write the hint subtitle

### Point down the features

feature points
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121346142/3493f566-65f8-4100-9f7c-f64d627d4fc5)

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
@jayanththalla Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
