### ISSUE TITLE
[Documentation Bug]: CSS move from index.html file to CSS file

### ISSUE THREAD

**Issue by Harshsaini001** [GameSphere-MultiPlayer/Physi-c-Tech#76]
### Describe the bug ✍️

In this the CSS is written in index.html file in between style tag.

### Provide step by step information reproduce the bug 📄

i will create a CSS File "style.css" and move CSS code from "index.html" file to "style .css" file. 

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@Harshsaini001 Don't spam pull requests, first get yourself the issue assigned.
