### ISSUE TITLE
Could change the style of exising scroll bar

### ISSUE THREAD

**Issue by uraj1** [GameSphere-MultiPlayer/Physi-c-Tech#79]
### 🎮 feature Request

The scroll bar is set to default style

### Point down the features

It can be changed according to theme of the webpage

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by aasthabagrawal** [comment]
Plz assign this task to me.

**Comment by Durgesh4993** [comment]
@aasthabagrawal Could you please explain more what you want to do, if possible you can also add screenshot.

**Comment by Deepthi-Ramineni** [comment]
@Durgesh4993  Can you please assign this to me?
