### ISSUE TITLE
[New Feature]: Adding footer

### ISSUE THREAD

**Issue by Aditi-P22** [GameSphere-MultiPlayer/Physi-c-Tech#8]
### 🎮 feature Request

The goal of this feature request is to implement a footer across all pages of our project repository. The footer should include essential links.
The footer adopts a clean and minimalistic design to maintain consistency with the project's overall aesthetic.
It utilizes contrasting colors and clear typography for improved readability and accessibility.
The layout is responsive, ensuring optimal viewing and interaction across various devices and screen sizes.

### Point down the features

Navigation Links: Clearly labeled links to important sections of the project, such as Home, Documentation, Contributing Guidelines, and Contact.
Social Media Icons: Icons linking to the project's official social media profiles for easy access and engagement.
Copyright Information: A copyright notice to protect the project's intellectual property rights.
Privacy Policy: Link to the project's privacy policy for transparency and compliance with data protection regulations.
Contact Information: An email address or contact form for users to reach out with inquiries or feedback.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Logic133** [comment]
i would like to work on this project . Please assign it to me

**Comment by Nih1tGupta** [comment]
Hello there ! .I would like to work on this project. please assign it to me.

**Comment by abhishekpandey26** [comment]
I'm a experienced front end developer. Kindly assign this to me and i will provide you a best design with necessary requirements.Please assign this to me under GSSOC'24

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Durgesh4993** [comment]
@abhishekpandey26 @Aditi-P22 @Nih1tGupta @Sheryar-bit @Anou25 Please raise any other issue, because someone is already working on it

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
