### ISSUE TITLE
[Bug]: Fixing the UI of About page

### ISSUE THREAD

**Issue by gaddevinay** [GameSphere-MultiPlayer/Physi-c-Tech#82]
### Give a brief about the bug ✍️

Making the about page more responsive for all devices.

### What is the expected behavior? 🤔

Expecting that about page is responsive.

### Provide step by step information reproduce the bug 📄

Using Css media query making more responsive.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@KomalSrivastava Raise a new issue regarding improvement of the UI, I will assign you that issue and then you can start working on it.

**Comment by KomalSrivastava** [comment]
@thevirengarg  The changes and enhancements made to the HTML , about.html  and CSS code for the Physi-c Tech website are:

1.The "why" section is updated with a list of reasons why Physi-c Tech is an innovative learning tool, with endless possibilities, and a community for users to join and share their discoveries.
2.The text on the webpage is styled with CSS, including animations for the "highlight" class, which causes the text to change color every few seconds, and the "animated-text" class, which causes the text to fade in when the page loads.
3.The "feature-title" class is updated to make the topic red.
4.The "btns" class is updated to align the buttons in the center.
These changes and enhancements improve the visual appeal and user experience of the Physi-c Tech website.
also here is continue written and it is showing play on website i can change it but am thinking to change little bit whole home page like add hover effect , in box etc.
![Screenshot 2024-05-23 212544](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/132221203/67bbf797-adeb-46ca-a237-f6daecc4d215) this i can improve and add animation effect to whole.
![play](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/132221203/6793a672-0c9a-4f51-9567-f05289d88604)
and am thinking to enhance it. i have changed it to this 
![correction](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/132221203/98a504da-0e9a-4444-87dc-f2519d268bed)
but am thinking to change this.
so, please assign me this project, i will work on it .

**Comment by gaddevinay** [comment]
@KomalSrivastava This issue is closed 
You think you can improve more create a new issue.
Admin also said that don't waste time here.

**Comment by KomalSrivastava** [comment]
@thevirengarg I can improve #39 and #42 which is about home page button and icon assign me this  task. I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible About page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience.

**Comment by KomalSrivastava** [comment]
@thevirengarg can you assign me #42 and #39 which is related to home page button improvement. I am confident that, if assigned this task, I will complete it promptly and to a high standard. My goal is to create a visually appealing and user-friendly About page that accurately represents our project and engages our audience. I am excited to contribute to this project under GSSoC and make a positive impact on our website.

I will use my skills in HTML, CSS, and JavaScript to create a responsive and accessible Home page that meets the needs of our users. I will also ensure that the page is optimized for search engines and follows best practices for web development.

I am confident that my contributions will help to improve the overall user experience of our website and make it a valuable resource for our audience.

**Comment by thevirengarg** [comment]
@KomalSrivastava Create new issues explaining what you can contribute. Don't comment on closed issues. I will assign you the issues which are created by you.
