### ISSUE TITLE
[Enhancement]: Making Buttons attractive and clear to understand.

### ISSUE THREAD

**Issue by HarshitGupta1511** [GameSphere-MultiPlayer/Physi-c-Tech#83]
### Do you want to have the enhancement of existing game ? 😀 Describe yourself..

Game enhancement- I will add hover effects in buttons to make it more attractive . moreover I will add proper spacing between them for clear understanding .

### Describe the solution you'd like

Solution steps- I will use hover effect under CSS code of the project and use css and html property to properly align things and make the homepage much more creative and attractive . please assign me this task @du

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by HarshitGupta1511** [comment]
please assign me this task @thevirengarg

**Comment by aasthabagrawal** [comment]
Plz assign this task to me

**Comment by thevirengarg** [comment]
> Plz assign this task to me

@aasthabagrawal This issue has already been assigned to someone else. You can raise a new issue regarding some other improvement or fixing a bug

**Comment by Durgesh4993** [comment]
@HarshitGupta1511 Please raise any other issue, because someone is already working on it..
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channels for all projects...

Thank you :)
