### ISSUE TITLE
[New Feature]: Enhancement the Popup Message

### ISSUE THREAD

**Issue by SrinivasDevolper** [GameSphere-MultiPlayer/Physi-c-Tech#84]
### 🎮 feature Request

**Prevent the playing when enter the popup message**

actual behaviour

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121508628/3924f08d-b54d-42f3-a09e-7ba27344e479

excepted behaviour

**Enhancement the Popup Message**

### Point down the features

feature points
**Prevent the playing when enter the popup message**

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by SrinivasDevolper** [comment]
now, The website is Not Working properly

https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121508628/7868537d-6bc6-4a38-8dec-c0ce0b342d64

**Comment by thevirengarg** [comment]
@SrinivasDevolper I have reported this issue to the project admin, He will look into it. 
Project Admin: @Durgesh4993

**Comment by thevirengarg** [comment]
@SrinivasDevolper Check now, its fixed.

**Comment by SrinivasDevolper** [comment]
I checked it, but it's again not working well


https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/121508628/032f5d8f-bd92-4f0a-ac4a-1f5b709af06f

**Comment by Durgesh4993** [comment]
@SrinivasDevolper Now you can start working on it
