### ISSUE TITLE
[New Feature]: Adding hover effect over the start menu

### ISSUE THREAD

**Issue by YadlaMani** [GameSphere-MultiPlayer/Physi-c-Tech#86]
### 🎮 feature Request

In start menu adding some kind of hover effect in the start menu
![image](https://github.com/GameSphere-MultiPlayer/Physi-c-Tech/assets/133841094/ca563f1f-da3a-44b5-a852-ec6a8813862e)

### Point down the features

adding hover effect

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@YadlaMani Similar issue has already been assigned to someone else, before raising an issue make sure you go through already assigned issues, to avoid raising an already assigned issue.
