### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by manyahegde** [GameSphere-MultiPlayer/Physi-c-Tech#92]
### Give a brief about the bug ✍️

1. There's a spacing issue  in the heading.
2. Unnecessary use of ':'. 
3. And the font family looks off. I would like to make it more attractive.

### What is the expected behavior? 🤔

Description

### Provide step by step information reproduce the bug 📄

Description

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by thevirengarg** [comment]
@manyahegde I have assigned you this issue but just correcting the spacing wont give you points for the contribution, improve the overall user interface.

**Comment by manyahegde** [comment]
okayy

**Comment by manyahegde** [comment]
> @manyahegde I have assigned you this issue but just correcting the spacing wont give you points for the contribution, improve the overall user interface.

okayy

**Comment by manyahegde** [comment]
@thevirengarg okayy

**Comment by manyahegde** [comment]
@thevirengarg I have created the PR, please add label and accept it. I have changed the ui other than spacing and punctuation issues.
